version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.4
  - dependency-name: NServiceBus
    versions:
    - 7.4.6
  - dependency-name: MarkdownSnippets.MsBuild
    versions:
    - 23.1.2
  - dependency-name: Verify.Xunit
    versions:
    - 10.9.0
    - 11.2.0
    - 11.4.0
